math:
	moth math_lib.moth -o math_lib.o -O3 -c --echo

io:
	moth io_lib.moth -o io_lib.o -O3 -c --echo

rand:
	moth rand_lib.moth -o rand_lib.o -O3 -c --echo

stdlib:
	moth stdlib_lib.moth -o stdlib_lib.o -O3 -c --echo
