main: hello_world fibonacci arrays lists

hello_world:
	moth hello_world.moth -o hello_world.o

fibonacci:
	moth fibonacci.moth -o fibonacci.o

arrays:
	moth arrays.moth -o arrays.o

lists:
	moth lists.moth -o lists.o

clean:
	rm *.o